{% set name = "confuse" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c9fe8474516a62397f8e52fcf89547bb2f2737b1a4a6f6dec11a286f0b3a7401

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - flit-core >=2,<4
  run:
    - python >=3.6
    - pyyaml

test:
  imports:
    - confuse

about:
  home: https://github.com/beetbox/confuse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: painless YAML configuration

  description: |
    Confuse is a configuration library for Python that uses YAML.
    It takes care of defaults, overrides, type checking, command-line
    integration, human-readable errors, and standard OS-specific locations.
  doc_url: http://confuse.readthedocs.org/
  dev_url: https://github.com/beetbox/confuse

extra:
  recipe-maintainers:
    - philip-khor
