{% set name = "confuse" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35c1b53e81be125f441bee535130559c935917b26aeaa61289010cd1f55c2b9e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=2,<4
    - poetry-core >=2.1
    - poethepoet >=0.32
  run:
    - python >={{ python_min }}
    - pyyaml

test:
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - confuse


about:
  home: https://github.com/beetbox/confuse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: painless YAML configuration

  description: |
    Confuse is a configuration library for Python that uses YAML.
    It takes care of defaults, overrides, type checking, command-line
    integration, human-readable errors, and standard OS-specific locations.
  doc_url: http://confuse.readthedocs.org/
  dev_url: https://github.com/beetbox/confuse

extra:
  recipe-maintainers:
    - philip-khor
