{% set name = "confuse" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7379a2ad49aaa862b79600cc070260c1b7974d349f4fa5e01f9afa6c4dd0611f

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=2,<4
  run:
    - python >={{ python_min }}
    - pyyaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - confuse

about:
  home: https://github.com/beetbox/confuse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: painless YAML configuration

  description: |
    Confuse is a configuration library for Python that uses YAML.
    It takes care of defaults, overrides, type checking, command-line
    integration, human-readable errors, and standard OS-specific locations.
  doc_url: http://confuse.readthedocs.org/
  dev_url: https://github.com/beetbox/confuse

extra:
  recipe-maintainers:
    - philip-khor
